import React from "react";
// Lucide icons used for visual interest
import { Code, Bot, Zap, Car } from "lucide-react";

const About = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="container mx-auto px-4 max-w-5xl">
        {/* --- Project Header/Hero Section --- */}
        <header className="bg-white p-8 rounded-xl shadow-2xl text-center mb-12">
          <p className="text-sm font-semibold uppercase tracking-wider text-red-600 mb-2">
            🚗 Car Showcase Project
          </p>
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4">
            Welcome to DreamWheel
          </h1>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            A demo built to level up full-stack development skills, featuring a
            unique twist: all car information and images are AI-generated for
            demonstration purposes only.
          </p>
        </header>

        {/* --- AI Concept Section --- */}
        <section className="py-12">
          <div className="grid md:grid-cols-2 gap-10 items-center bg-white p-8 rounded-xl shadow-lg">
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-4 border-l-4 border-red-600 pl-4">
                The Creative Twist: AI-Generated Data 🤖
              </h2>
              <p className="text-gray-600 leading-relaxed mb-4">
                This site features a collection of real car brands and models,
                but all the data you see—like descriptions, features, and prices
                —is creatively generated by AI tools.
              </p>
              <p className="text-gray-600 leading-relaxed">
                The purpose is to explore how AI can be used to simulate
                realistic data for app development. This is purely a fun
                learning experience that mixes tech, creativity, and design.
                None of the details represent real-world car specifications or
                pricing.
              </p>
            </div>
            <div className="p-4 bg-red-50 rounded-lg text-center border border-red-200">
              <Bot
                className="text-red-600 mx-auto mb-3"
                size={48}
                strokeWidth={2}
              />
              <p className="font-semibold text-lg text-gray-800">
                *Data is AI-Simulated.*
              </p>
              <p className="text-sm text-gray-600">
                (Not real-world specifications or prices)
              </p>
            </div>
          </div>
        </section>

        {/* --- Tech Stack Section --- */}
        <section className="py-12">
          <h2 className="text-3xl font-bold text-center text-gray-800 mb-10">
            Technology Stack ⚙️
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Frontend Card */}
            <div className="p-6 bg-white rounded-xl shadow-lg border-t-4 border-blue-500">
              <div className="flex items-center space-x-4 mb-4">
                <Code className="text-blue-600" size={32} />
                <h3 className="text-xl font-bold text-gray-800">🖥️ Frontend</h3>
              </div>
              <ul className="space-y-2 text-gray-600 list-disc list-inside pl-2">
                <li>Built with React for a modular component structure.</li>
                <li>
                  Uses Vite for a clean, fast, and responsive UI with quick
                  reloading.
                </li>
                <li>
                  Styled beautifully with Tailwind CSS for utility-first design.
                </li>
              </ul>
            </div>

            {/* Backend Card */}
            <div className="p-6 bg-white rounded-xl shadow-lg border-t-4 border-green-500">
              <div className="flex items-center space-x-4 mb-4">
                <Zap className="text-green-600" size={32} />
                <h3 className="text-xl font-bold text-gray-800">
                  ⚙️ Backend & Data
                </h3>
              </div>
              <ul className="space-y-2 text-gray-600 list-disc list-inside pl-2">
                <li>Powered by Node.js and Express .</li>
                <li>Serves AI-generated car data through REST APIs .</li>
                <li>
                  A demonstration of full-stack integration and data serving.
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* --- Closing Thank You --- */}
        <section className="py-12 text-center mt-8">
          <p className="text-xl font-semibold text-gray-700 mb-4">
            Thanks for checking it out! 👏
          </p>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Hope you enjoy scrolling through these AI-styled rides as much as I
            enjoyed building the project. Feel free to explore and check out the
            code!
          </p>
          <a
            href="/"
            className="inline-block mt-6 px-8 py-3 text-lg font-bold text-white bg-red-600 rounded-lg hover:bg-red-700 transition duration-300 shadow-xl"
          >
            Start Exploring Cars <Car size={20} className="inline ml-2" />
          </a>
        </section>
      </div>
    </div>
  );
};

export default About;
